spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/iis_baza
spring.datasource.username=postgres
spring.datasource.password=ftn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

app.jwt.secret=nF9eTqVwEHn7OoK4H3sVKIHl6tc8uDHT6AVKbATTkw4
app.jwt.expiration-ms=86400000
